name: 自动部署

on:
    push:
        branches:
            - source # default branch

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  # If your repository depends on submodule, please see: https://github.com/actions/checkout
                  submodules: recursive
            - name: Use Node.js 20.11.1
              uses: actions/setup-node@v4
              with:
                  # Examples: 20, 18.19, >=16.20.2, lts/Iron, lts/Hydrogen, *, latest, current, node
                  # Ref: https://github.com/actions/setup-node#supported-version-syntax
                  node-version: "20.11.1"
            - name: Cache NPM dependencies
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: ${{ runner.OS }}-npm-cache
                  restore-keys: |
                      ${{ runner.OS }}-npm-cache
            - name: 安装 Hexo
              run: npm install hexo-cli -g

            - name: 缓存 Hexo
              uses: actions/cache@v4
              id: cache
              with:
                  path: node_modules
                  key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}

            - name: 生成静态文件
              run: |
               hexo clean
               hexo generate
   
            - name: Deploy to GitHub Pages
             
              uses: actions/deploy-pages@v4
              with:
                repository-name: Yumi0606/yumi.github.io
                token: ${{ secrets.GITHUB_TOKEN }}
                folder: public
                branch: source
                id-token: write